// Code generated by mockery v1.0.0. DO NOT EDIT.

// Regenerate this file using `make mocks`.

package mocks

import io "io"
import mock "github.com/stretchr/testify/mock"

// PDFServer is an autogenerated mock type for the PDFServer type
type PDFServer struct {
	mock.Mock
}

// Convert provides a mock function with given fields: name, extension, file
func (_m *PDFServer) Convert(name string, extension string, file io.Reader) (io.ReadCloser, error) {
	ret := _m.Called(name, extension, file)

	var r0 io.ReadCloser
	if rf, ok := ret.Get(0).(func(string, string, io.Reader) io.ReadCloser); ok {
		r0 = rf(name, extension, file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, io.Reader) error); ok {
		r1 = rf(name, extension, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Status provides a mock function with given fields:
func (_m *PDFServer) Status() (bool, error) {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
