// Code generated by mockery v1.0.0. DO NOT EDIT.

// Regenerate this file using `make mocks`.

package mocks

import io "io"
import mock "github.com/stretchr/testify/mock"

// TOPDF is an autogenerated mock type for the TOPDF type
type TOPDF struct {
	mock.Mock
}

// CheckServerStatus provides a mock function with given fields:
func (_m *TOPDF) CheckServerStatus() (bool, error) {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPDF provides a mock function with given fields: userID, fileID
func (_m *TOPDF) GetPDF(userID string, fileID string) (io.ReadCloser, error) {
	ret := _m.Called(userID, fileID)

	var r0 io.ReadCloser
	if rf, ok := ret.Get(0).(func(string, string) io.ReadCloser); ok {
		r0 = rf(userID, fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, fileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
